Icon
calidae/systelab-components pull request #3
Opened 2017-11-29 16:00 UTC by xevops

2017-11-29 16:08 UTC, afontcu requested changes
Les classes que no siguin una adaptació de Boostrap (com .btn) han de portar el prefix .slab- per distingir-les de les del propi framework. En aquest cas les dels icones el necessiten.

2017-11-29 16:28 UTC, xevops commented
afegits prefixos slab-

2017-11-29 16:39 UTC, afontcu requested changes
A la classe `.position-right-icon` també hauríem d'afegir-hi el prefix. El dubte que tinc és si podríem moure-la a _icon.scss o no...

Un dubte, els icones es veuen? Ho dic perquè em sembla que bootstrap no inclou font awesome per defecte com sí que feia UIKit (crec), i el `.slab-icon` està setejant aquest font-family. Si es veuen és que potser no cal definir-lo.

2017-11-30 08:53 UTC, xevops commented
Bootstrap no inclou icones "de saque" pel que el fontawesome de moment l'he esborrat ja que en principi no s'està utilitzant i les icones que utilitzen tenen la seva font propia del icomoon. Nomès vaig trobar una icona del uikit (uk-icon-calendar) que la vaig canviar per la seva del icomoon.

Les icones es veuen sobretot a la pestanya icons, i les de calendari a la pestanya datepicker. Les úniques classes que no he pogut provar son les de slab-icon-medium ja que es veuen dins el datepicker que no funciona.

2017-11-30 08:56 UTC, afontcu approved these changes

2017-11-30 12:03 UTC, oriolfg approved these changes

2017-11-30 12:19 UTC, merged